### ISSUE TITLE
 Hello,  this is really amazing script，what is the reason for this error? thank you vary much

### ISSUE THREAD

**Issue by luffymu** [robertjoosten/maya-retarget-blendshape#1]
![qq 20180917161907](https://user-images.githubusercontent.com/43170958/45612468-948d9400-ba95-11e8-8c87-10cc895892fc.jpg)

**Comment by robertjoosten** [comment]
Hello, to me it looks like the mel script doesn't like a path with spaces.
Could you put the script somewhere there is no space in the path and try again? Please let me know if that solved the issue, if it did I will look into upgrading the mel file to work with spaced paths as well.
